### ISSUE TITLE
Ability for tools/equipment to modify staminadrain

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/StaminaClimb#29]
### Is your feature request related to a problem?

Freshies and old players have the same stamina. Lets those who have played for long the ability to modify their total stamina.

### Describe the solution you'd like.

Since StaminaClimb is already inspired from BotW:

**Climbing gear**: Boost to climbing speed

**Potions or something**: Temporary / permanent stamina boost

### Describe alternatives you've considered.

:)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Confusman** [comment]
### **Climbing Ideas:**
_With these additions, the default climbing speed should be lowered_

**Different types of climbing gear**
- Shoes and Gloves (boots and chestplate slot) | Increases climbing speed and max stamina respectivley
- Harness (leggings slot) | Allows for the ability to use bolts (see next idea) but lowers your max stamina and speed
_These 3 'armour pieces' should have very little, if any defence_

**Specific Items**
- Anchor points | A single use item that lets you hang on the wall and regain stamina (as oppose to akwardly placing a block beneath you before you fall, or in adventure mode would be a good alternative since you can't really place many blocks)
- Chalk bag | An item that whilst in your hotbar decreases stamina drain (should have durability that can be repaired with chalk)
- Chalk | A material used with chalk bag

**Climbing Systems**
- Your stamina could drain at different rates depending on how full your inventory is.
-Empty gives like a 10% speed boost
-Having 9 inventory slots filled gives no boost
-Every 9 inventory slots taken up after gives a 5% speed decrease
-Adding to a make a max debuff of 15% if every single slot is filled (would also make backpacks more valuable)
- Horizontal climbing can negate less stamina then vertical climbing
- Could add a bit of randomness to climbing, like slight speed changes or stamina drain rates
